import type { IHabitTemplate } from "@/types";

// Category gradient colours used by the TemplateSelector card UI
export const TEMPLATE_CATEGORY_STYLES: Record<
  string,
  { from: string; to: string }
> = {
  Fitness:           { from: "#3b82f6", to: "#6366f1" },
  Health:            { from: "#22c55e", to: "#10b981" },
  Productivity:      { from: "#8b5cf6", to: "#6366f1" },
  Learning:          { from: "#f97316", to: "#f59e0b" },
  "Mental Wellness": { from: "#ec4899", to: "#8b5cf6" },
  Lifestyle:         { from: "#14b8a6", to: "#0ea5e9" },
};

export const HABIT_TEMPLATES: IHabitTemplate[] = [
  // ── Fitness ──────────────────────────────────────────────────────
  {
    id: "tpl_morning_walk",
    title: "Morning Walk",
    description: "Start your day with a refreshing walk outside.",
    category: "Fitness",
    emoji: "🚶",
    color: "#3b82f6",
    targetType: "boolean",
    targetValue: 1,
    frequencyType: "daily",
  },
  {
    id: "tpl_gym_workout",
    title: "Gym Workout",
    description: "Hit the gym and build strength.",
    category: "Fitness",
    emoji: "🏋️",
    color: "#6366f1",
    targetType: "boolean",
    targetValue: 1,
    frequencyType: "custom",
    frequencyDays: [1, 3, 5], // Mon, Wed, Fri
  },
  {
    id: "tpl_stretching",
    title: "Daily Stretching",
    description: "Keep your body flexible with a quick stretch session.",
    category: "Fitness",
    emoji: "🤸",
    color: "#0ea5e9",
    targetType: "duration",
    targetValue: 10,
    frequencyType: "daily",
  },

  // ── Health ────────────────────────────────────────────────────────
  {
    id: "tpl_drink_water",
    title: "Drink 8 Glasses of Water",
    description: "Stay hydrated throughout the day.",
    category: "Health",
    emoji: "💧",
    color: "#22c55e",
    targetType: "count",
    targetValue: 8,
    frequencyType: "daily",
  },
  {
    id: "tpl_sleep_8",
    title: "Sleep 8 Hours",
    description: "Protect your sleep for peak energy and focus.",
    category: "Health",
    emoji: "😴",
    color: "#10b981",
    targetType: "boolean",
    targetValue: 1,
    frequencyType: "daily",
  },
  {
    id: "tpl_vitamins",
    title: "Take Vitamins",
    description: "Don't skip your daily supplements.",
    category: "Health",
    emoji: "💊",
    color: "#14b8a6",
    targetType: "boolean",
    targetValue: 1,
    frequencyType: "daily",
  },

  // ── Productivity ──────────────────────────────────────────────────
  {
    id: "tpl_deep_work",
    title: "Deep Work Session",
    description: "Focus without distractions on your most important task.",
    category: "Productivity",
    emoji: "🎯",
    color: "#8b5cf6",
    targetType: "duration",
    targetValue: 120,
    frequencyType: "daily",
  },
  {
    id: "tpl_plan_day",
    title: "Plan Your Day",
    description: "Spend 5 minutes planning before you start working.",
    category: "Productivity",
    emoji: "📋",
    color: "#6366f1",
    targetType: "boolean",
    targetValue: 1,
    frequencyType: "daily",
  },
  {
    id: "tpl_no_phone_morning",
    title: "No Phone First Hour",
    description: "Avoid screens for the first hour after waking up.",
    category: "Productivity",
    emoji: "📵",
    color: "#7c3aed",
    targetType: "boolean",
    targetValue: 1,
    frequencyType: "daily",
  },

  // ── Learning ──────────────────────────────────────────────────────
  {
    id: "tpl_read_pages",
    title: "Read 20 Pages",
    description: "Read a little every day to keep growing.",
    category: "Learning",
    emoji: "📖",
    color: "#f97316",
    targetType: "count",
    targetValue: 20,
    frequencyType: "daily",
  },
  {
    id: "tpl_practice_coding",
    title: "Practice Coding",
    description: "Write code every day to sharpen your skills.",
    category: "Learning",
    emoji: "💻",
    color: "#f59e0b",
    targetType: "duration",
    targetValue: 30,
    frequencyType: "daily",
  },
  {
    id: "tpl_learn_language",
    title: "Language Practice",
    description: "A few minutes of language learning every day.",
    category: "Learning",
    emoji: "🗣️",
    color: "#ea580c",
    targetType: "duration",
    targetValue: 15,
    frequencyType: "daily",
  },

  // ── Mental Wellness ───────────────────────────────────────────────
  {
    id: "tpl_meditation",
    title: "Meditation",
    description: "Quiet your mind with a daily meditation practice.",
    category: "Mental Wellness",
    emoji: "🧘",
    color: "#ec4899",
    targetType: "duration",
    targetValue: 10,
    frequencyType: "daily",
  },
  {
    id: "tpl_journaling",
    title: "Journaling",
    description: "Write down your thoughts and feelings each day.",
    category: "Mental Wellness",
    emoji: "✍️",
    color: "#db2777",
    targetType: "boolean",
    targetValue: 1,
    frequencyType: "daily",
  },
  {
    id: "tpl_gratitude",
    title: "Gratitude Practice",
    description: "Write 3 things you're grateful for.",
    category: "Mental Wellness",
    emoji: "🙏",
    color: "#a855f7",
    targetType: "boolean",
    targetValue: 1,
    frequencyType: "daily",
  },

  // ── Lifestyle ─────────────────────────────────────────────────────
  {
    id: "tpl_wake_early",
    title: "Wake Up Early",
    description: "Rise before 7 AM to own the morning.",
    category: "Lifestyle",
    emoji: "⏰",
    color: "#14b8a6",
    targetType: "boolean",
    targetValue: 1,
    frequencyType: "daily",
  },
  {
    id: "tpl_no_sugar",
    title: "No Sugar Day",
    description: "Avoid added sugar to improve energy and focus.",
    category: "Lifestyle",
    emoji: "🚫",
    color: "#0891b2",
    targetType: "boolean",
    targetValue: 1,
    frequencyType: "daily",
  },
  {
    id: "tpl_evening_walk",
    title: "Evening Walk",
    description: "Wind down with a peaceful walk after dinner.",
    category: "Lifestyle",
    emoji: "🌅",
    color: "#0ea5e9",
    targetType: "boolean",
    targetValue: 1,
    frequencyType: "daily",
  },
];

export const TEMPLATE_CATEGORIES = [
  "All",
  "Fitness",
  "Health",
  "Productivity",
  "Learning",
  "Mental Wellness",
  "Lifestyle",
] as const;
